// Code generated by "stringer -type=itemType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[tDate-0]
	_ = x[tState-1]
	_ = x[tPayee-2]
	_ = x[tAccount-3]
	_ = x[tCommodity-4]
	_ = x[tAmount-5]
	_ = x[tComment-6]
}

const _itemType_name = "tDatetStatetPayeetAccounttCurrencytAmounttComment"

var _itemType_index = [...]uint8{0, 5, 11, 17, 25, 34, 41, 49}

func (i itemType) String() string {
	if i < 0 || i >= itemType(len(_itemType_index)-1) {
		return "itemType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _itemType_name[_itemType_index[i]:_itemType_index[i+1]]
}
