// Code generated by "stringer -type=itemType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[tEmptyLine-0]
	_ = x[tDate-1]
	_ = x[tState-2]
	_ = x[tPayee-3]
	_ = x[tAccount-4]
	_ = x[tCommodity-5]
	_ = x[tAmount-6]
	_ = x[tComment-7]
	_ = x[tEOF-8]
}

const _itemType_name = "tEmptyLinetDatetStatetPayeetAccounttCommoditytAmounttCommenttEOF"

var _itemType_index = [...]uint8{0, 10, 15, 21, 27, 35, 45, 52, 60, 64}

func (i itemType) String() string {
	if i < 0 || i >= itemType(len(_itemType_index)-1) {
		return "itemType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _itemType_name[_itemType_index[i]:_itemType_index[i+1]]
}
