// Code generated by "stringer -type=transactionState"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[tNoState-0]
	_ = x[tUncleared-1]
	_ = x[tCleared-2]
}

const _transactionState_name = "tNoStatetUnclearedtCleared"

var _transactionState_index = [...]uint8{0, 8, 18, 26}

func (i transactionState) String() string {
	if i < 0 || i >= transactionState(len(_transactionState_index)-1) {
		return "transactionState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _transactionState_name[_transactionState_index[i]:_transactionState_index[i+1]]
}
