// Code generated by "stringer -type=itemType"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[emptyLineItem-0]
	_ = x[dateItem-1]
	_ = x[stateItem-2]
	_ = x[payeeItem-3]
	_ = x[accountItem-4]
	_ = x[commodityItem-5]
	_ = x[amountItem-6]
	_ = x[commentItem-7]
	_ = x[eofItem-8]
}

const _itemType_name = "emptyLineItemdateItemstateItempayeeItemaccountItemcommodityItemamountItemcommentItemeofItem"

var _itemType_index = [...]uint8{0, 13, 21, 30, 39, 50, 63, 73, 84, 91}

func (i itemType) String() string {
	if i < 0 || i >= itemType(len(_itemType_index)-1) {
		return "itemType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _itemType_name[_itemType_index[i]:_itemType_index[i+1]]
}
