// Code generated by "stringer -type=itemType"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[emptyLineItem-0]
	_ = x[includeItem-1]
	_ = x[dateItem-2]
	_ = x[stateItem-3]
	_ = x[payeeItem-4]
	_ = x[accountItem-5]
	_ = x[commodityItem-6]
	_ = x[amountItem-7]
	_ = x[commentItem-8]
	_ = x[periodItem-9]
	_ = x[eofItem-10]
}

const _itemType_name = "emptyLineItemincludeItemdateItemstateItempayeeItemaccountItemcommodityItemamountItemcommentItemperiodItemeofItem"

var _itemType_index = [...]uint8{0, 13, 24, 32, 41, 50, 61, 74, 84, 95, 105, 112}

func (i itemType) String() string {
	if i < 0 || i >= itemType(len(_itemType_index)-1) {
		return "itemType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _itemType_name[_itemType_index[i]:_itemType_index[i+1]]
}
