// Code generated by "stringer -type=transactionType"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[normalTransaction-0]
	_ = x[periodicTransaction-1]
}

const _transactionType_name = "normalTransactionperiodicTransaction"

var _transactionType_index = [...]uint8{0, 17, 36}

func (i transactionType) String() string {
	if i < 0 || i >= transactionType(len(_transactionType_index)-1) {
		return "transactionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _transactionType_name[_transactionType_index[i]:_transactionType_index[i+1]]
}
