// Code generated by "stringer -type=PeriodType"; DO NOT EDIT.

package journal

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PNone-0]
	_ = x[PDaily-1]
	_ = x[PWeekly-2]
	_ = x[PMonthly-3]
	_ = x[PQuarterly-4]
	_ = x[PYearly-5]
	_ = x[PBiweekly-6]
	_ = x[PFortnightly-7]
	_ = x[PBiMonthly-8]
}

const _PeriodType_name = "PNonePDailyPWeeklyPMonthlyPQuarterlyPYearlyPBiweeklyPFortnightlyPBiMonthly"

var _PeriodType_index = [...]uint8{0, 5, 11, 18, 26, 36, 43, 52, 64, 74}

func (i PeriodType) String() string {
	if i < 0 || i >= PeriodType(len(_PeriodType_index)-1) {
		return "PeriodType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PeriodType_name[_PeriodType_index[i]:_PeriodType_index[i+1]]
}
